# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `heroicons` gem.
# Please instead update this file by running `bin/tapioca gem heroicons`.


# source://heroicons//lib/heroicons/engine.rb#1
module Heroicons
  class << self
    # source://heroicons//lib/heroicons/configuration.rb#13
    def configuration; end

    # source://heroicons//lib/heroicons/configuration.rb#17
    def configuration=(config); end

    # @yield [configuration]
    #
    # source://heroicons//lib/heroicons/configuration.rb#21
    def configure; end

    # source://heroicons//lib/heroicons/engine.rb#3
    def railtie_helpers_paths; end

    # source://heroicons//lib/heroicons/engine.rb#3
    def railtie_namespace; end

    # source://heroicons//lib/heroicons/engine.rb#3
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://heroicons//lib/heroicons.rb#7
    def root; end

    # source://heroicons//lib/heroicons/engine.rb#3
    def table_name_prefix; end

    # source://heroicons//lib/heroicons/engine.rb#3
    def use_relative_model_naming?; end
  end
end

# source://heroicons//lib/heroicons/configuration.rb#2
class Heroicons::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://heroicons//lib/heroicons/configuration.rb#8
  def initialize; end

  # Returns the value of attribute default_class.
  #
  # source://heroicons//lib/heroicons/configuration.rb#6
  def default_class; end

  # Sets the attribute default_class
  #
  # @param value the value to set the attribute default_class to.
  #
  # source://heroicons//lib/heroicons/configuration.rb#6
  def default_class=(_arg0); end

  # Returns the value of attribute variant.
  #
  # source://heroicons//lib/heroicons/configuration.rb#5
  def variant; end

  # Sets the attribute variant
  #
  # @param value the value to set the attribute variant to.
  #
  # source://heroicons//lib/heroicons/configuration.rb#5
  def variant=(_arg0); end
end

# source://heroicons//lib/heroicons/configuration.rb#3
Heroicons::Configuration::DEFAULT_VARIANT = T.let(T.unsafe(nil), Symbol)

# source://heroicons//lib/heroicons/engine.rb#2
class Heroicons::Engine < ::Rails::Engine; end

# source://heroicons//lib/heroicons/helper.rb#2
module Heroicons::Helper
  # source://heroicons//lib/heroicons/helper.rb#3
  def heroicon(name, variant: T.unsafe(nil), options: T.unsafe(nil), path_options: T.unsafe(nil)); end
end

# source://heroicons//lib/heroicons/icon.rb#2
class Heroicons::Icon
  # @return [Icon] a new instance of Icon
  #
  # source://heroicons//lib/heroicons/icon.rb#5
  def initialize(name:, variant:, options:, path_options:); end

  # Returns the value of attribute name.
  #
  # source://heroicons//lib/heroicons/icon.rb#3
  def name; end

  # Returns the value of attribute options.
  #
  # source://heroicons//lib/heroicons/icon.rb#3
  def options; end

  # Returns the value of attribute path_options.
  #
  # source://heroicons//lib/heroicons/icon.rb#3
  def path_options; end

  # source://heroicons//lib/heroicons/icon.rb#12
  def render; end

  # Returns the value of attribute variant.
  #
  # source://heroicons//lib/heroicons/icon.rb#3
  def variant; end

  private

  # source://heroicons//lib/heroicons/icon.rb#60
  def additional_class_list; end

  # source://heroicons//lib/heroicons/icon.rb#52
  def combine_classes_with_default_class; end

  # source://heroicons//lib/heroicons/icon.rb#64
  def default_class; end

  # source://heroicons//lib/heroicons/icon.rb#74
  def default_class_config; end

  # source://heroicons//lib/heroicons/icon.rb#56
  def default_class_list; end

  # @return [Boolean]
  #
  # source://heroicons//lib/heroicons/icon.rb#78
  def disable_default_class?; end

  # source://heroicons//lib/heroicons/icon.rb#90
  def file; end

  # source://heroicons//lib/heroicons/icon.rb#96
  def file_path; end

  # Prepends the default CSS class name for an icon. You can provide a String, which will apply
  # to all icons, or a Hash, which will apply to the specified variant.
  #
  # @example
  #   Heroicons.configure do |config|
  #   config.default_class = { solid: "size-5", outline: "size-6", mini: "size-4", micro: "size-4" }
  #   end
  #
  #   #=> <svg class="size-5">...</svg>
  #
  # source://heroicons//lib/heroicons/icon.rb#46
  def prepend_default_class_name; end

  # source://heroicons//lib/heroicons/icon.rb#82
  def safe_variant(provided_variant); end

  # source://heroicons//lib/heroicons/icon.rb#100
  def warning; end

  class << self
    # source://heroicons//lib/heroicons/icon.rb#115
    def render(**kwargs); end
  end
end
