# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `html2text` gem.
# Please instead update this file by running `bin/tapioca gem html2text`.


# source://html2text//lib/html2text.rb#5
class Html2Text
  # @return [Html2Text] a new instance of Html2Text
  #
  # source://html2text//lib/html2text.rb#8
  def initialize(doc); end

  # source://html2text//lib/html2text.rb#45
  def convert; end

  # Returns the value of attribute doc.
  #
  # source://html2text//lib/html2text.rb#6
  def doc; end

  # source://html2text//lib/html2text.rb#54
  def remove_leading_and_trailing_whitespace(text); end

  private

  # source://html2text//lib/html2text.rb#219
  def image_text(node); end

  # source://html2text//lib/html2text.rb#91
  def iterate_over(node); end

  # @return [Boolean]
  #
  # source://html2text//lib/html2text.rb#242
  def next_node_is_text?(node); end

  # source://html2text//lib/html2text.rb#229
  def next_node_name(node); end

  # source://html2text//lib/html2text.rb#122
  def prefix_whitespace(node); end

  # @return [Boolean]
  #
  # source://html2text//lib/html2text.rb#259
  def previous_node_is_text?(node); end

  # source://html2text//lib/html2text.rb#246
  def previous_node_name(node); end

  # source://html2text//lib/html2text.rb#76
  def remove_unnecessary_empty_lines(text); end

  # source://html2text//lib/html2text.rb#153
  def suffix_whitespace(node); end

  # source://html2text//lib/html2text.rb#80
  def trimmed_whitespace(text); end

  # links are returned in [text](link) format
  #
  # source://html2text//lib/html2text.rb#179
  def wrap_link(node, output); end

  class << self
    # source://html2text//lib/html2text.rb#12
    def convert(html); end

    # source://html2text//lib/html2text.rb#33
    def fix_newlines(text); end

    # source://html2text//lib/html2text.rb#39
    def replace_entities(text); end

    private

    # @return [Boolean]
    #
    # source://html2text//lib/html2text.rb#70
    def office_document?(text); end
  end
end

# source://html2text//lib/html2text.rb#52
Html2Text::DO_NOT_TOUCH_WHITESPACE = T.let(T.unsafe(nil), String)
