# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lexxy` gem.
# Please instead update this file by running `bin/tapioca gem lexxy`.


# source://lexxy//lib/action_text/attachables/remote_video.rb#1
module ActionText; end

module ActionText::Attachable
  extend ::Lexxy::Attachable

  mixes_in_class_methods ::ActionText::Attachable::ClassMethods
end

# source://lexxy//lib/action_text/attachables/remote_video.rb#2
module ActionText::Attachables; end

# source://lexxy//lib/action_text/attachables/remote_video.rb#3
class ActionText::Attachables::RemoteVideo
  extend ::ActiveModel::Naming

  # @return [RemoteVideo] a new instance of RemoteVideo
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#29
  def initialize(attributes = T.unsafe(nil)); end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#37
  def attachable_plain_text_representation(caption); end

  # Returns the value of attribute content_type.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def content_type; end

  # Returns the value of attribute filename.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def filename; end

  # Returns the value of attribute height.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def height; end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#4
  def model_name(&_arg0); end

  # source://lexxy//lib/action_text/attachables/remote_video.rb#41
  def to_partial_path; end

  # Returns the value of attribute url.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def url; end

  # Returns the value of attribute width.
  #
  # source://lexxy//lib/action_text/attachables/remote_video.rb#27
  def width; end

  class << self
    # source://lexxy//lib/action_text/attachables/remote_video.rb#7
    def from_node(node); end

    private

    # source://lexxy//lib/action_text/attachables/remote_video.rb#18
    def attributes_from_node(node); end

    # @return [Boolean]
    #
    # source://lexxy//lib/action_text/attachables/remote_video.rb#14
    def content_type_is_video?(content_type); end
  end
end

module ActionText::TagHelper; end
module Actiontext; end
module Actiontext::Lexical; end

class Actiontext::Lexical::ApplicationController < ::ActionController::Base
  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end

  class << self
    def _routes; end

    private

    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Actiontext::Lexical::ApplicationController::HelperMethods
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Lexxy::TagHelper
  include ::InertiaRails::Helper
  include ::InertiaRails::AssetHelper
  include ::ViteRails::TagHelpers
  include ::ActionController::Base::HelperMethods
  include ::Actiontext::Lexical::ApplicationHelper
  include ::ApplicationHelper
end

module Actiontext::Lexical::ApplicationHelper; end
class Actiontext::Lexical::ApplicationJob < ::ActiveJob::Base; end

class Actiontext::Lexical::ApplicationRecord < ::ActiveRecord::Base
  include ::Actiontext::Lexical::ApplicationRecord::GeneratedAttributeMethods
  include ::Actiontext::Lexical::ApplicationRecord::GeneratedAssociationMethods

  class << self
    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Actiontext::Lexical::ApplicationRecord::GeneratedAssociationMethods; end
module Actiontext::Lexical::ApplicationRecord::GeneratedAttributeMethods; end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#1
module ActiveStorage; end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#2
module ActiveStorage::BlobWithPreviewUrl
  # source://lexxy//lib/active_storage/blob_with_preview_url.rb#5
  def as_json(options = T.unsafe(nil)); end
end

# source://lexxy//lib/active_storage/blob_with_preview_url.rb#3
ActiveStorage::BlobWithPreviewUrl::PREVIEW_SIZE = T.let(T.unsafe(nil), Array)

# source://lexxy//lib/lexxy/version.rb#1
module Lexxy
  class << self
    # source://lexxy//lib/lexxy.rb#5
    def override_action_text_defaults; end

    # source://lexxy//lib/lexxy/engine.rb#11
    def railtie_helpers_paths; end

    # source://lexxy//lib/lexxy/engine.rb#11
    def railtie_namespace; end

    # source://lexxy//lib/lexxy/engine.rb#11
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://lexxy//lib/lexxy/engine.rb#11
    def table_name_prefix; end

    # source://lexxy//lib/lexxy/engine.rb#11
    def use_relative_model_naming?; end
  end
end

# source://lexxy//lib/lexxy/action_text_tag.rb#2
module Lexxy::ActionTextTag
  # source://lexxy//lib/lexxy/action_text_tag.rb#3
  def initialize(object_name, method_name, template_object, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/action_text_tag.rb#9
  def lexxy_render; end
end

# source://lexxy//lib/lexxy/attachable.rb#4
module Lexxy::Attachable
  # source://lexxy//lib/lexxy/attachable.rb#5
  def from_node(node); end
end

# source://lexxy//lib/lexxy/engine.rb#10
class Lexxy::Engine < ::Rails::Engine; end

# source://lexxy//lib/lexxy/form_builder.rb#2
module Lexxy::FormBuilder
  # source://lexxy//lib/lexxy/form_builder.rb#7
  def lexxy_rich_text_area(method, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/form_builder.rb#3
  def lexxy_rich_textarea(method, options = T.unsafe(nil), &block); end
end

# source://lexxy//lib/lexxy/form_helper.rb#2
module Lexxy::FormHelper
  # source://lexxy//lib/lexxy/form_helper.rb#7
  def lexxy_rich_text_area(object_name, method, options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/form_helper.rb#3
  def lexxy_rich_textarea(object_name, method, options = T.unsafe(nil), &block); end
end

# source://lexxy//lib/lexxy/rich_text_area_tag.rb#2
module Lexxy::TagHelper
  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#21
  def lexxy_rich_text_area_tag(name, value = T.unsafe(nil), options = T.unsafe(nil), &block); end

  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#3
  def lexxy_rich_textarea_tag(name, value = T.unsafe(nil), options = T.unsafe(nil), &block); end

  private

  # Tempoary: we need to *adaptarize* action text
  #
  # source://lexxy//lib/lexxy/rich_text_area_tag.rb#25
  def render_custom_attachments_in(value); end
end

# source://lexxy//lib/lexxy/version.rb#2
Lexxy::VERSION = T.let(T.unsafe(nil), String)
