app = "smallerworld"
primary_region = "yyz"
kill_signal = "SIGINT"
swap_size_mb = 1024

[deploy]
  strategy = "canary"
  release_command = "bin/deploy"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

[services.concurrency]
  type = "requests"
  hard_limit = 60
  soft_limit = 20

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"
  method = "get"
  path = "/up"
  protocol = "http"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
