/**
 * Generated by: GPT-5 Codex
 * Last modified: 2025-10-27 00:00:00 UTC
 *
 * This code was AI-generated and may require human review and testing.
 */
import { Image, Radio, type RadioGroupProps } from "@mantine/core";
import bkdkImage from "~/assets/images/bakudeku.jpg";

import NoneIcon from "~icons/heroicons/no-symbol-20-solid";

import { USER_THEMES, userThemeThumbnailSrc } from "~/helpers/userThemes";
import { type UserTheme } from "~/types";

import classes from "./UserThemeRadioGroup.module.css";

export interface UserThemeRadioGroupProps
  extends Omit<RadioGroupProps, "children"> {
  extraOptions?: { value: string; imageSrc?: string }[];
}

const UserThemeRadioGroup: FC<UserThemeRadioGroupProps> = props => (
  <Radio.Group label="your page theme" labelProps={{ mb: 8 }} {...props}>
    <Group justify="center" gap={6} wrap="wrap">
      <RadioCard theme={null} />
      {USER_THEMES.map(theme => (
        <RadioCard key={theme} {...{ theme }} />
      ))}
      {props.extraOptions?.map(option => (
        <RadioCard
          key={option.value}
          theme={option.value}
          imageSrc={option.imageSrc ?? bkdkImage}
        />
      ))}
    </Group>
  </Radio.Group>
);

export default UserThemeRadioGroup;

interface RadioCardProps {
  theme: UserTheme | string | null;
  imageSrc?: string;
}

const RadioCard: FC<RadioCardProps> = ({ theme, imageSrc }) => {
  return (
    <Radio.Card className={classes.radioCard} value={theme ?? ""}>
      {theme ? (
        <Image src={imageSrc ?? userThemeThumbnailSrc(theme as UserTheme)} />
      ) : (
        <Center className={classes.noTheme}>
          <Box component={NoneIcon} fz={24} c="dimmed" />
        </Center>
      )}
    </Radio.Card>
  );
};
