/**
 * Generated by: GPT-5 Codex
 * Last modified: 2025-10-27 00:01:00 UTC
 *
 * This code was AI-generated and may require human review and testing.
 */
import { useComputedColorScheme } from "@mantine/core";
import bkdkImage from "~/assets/images/bakudeku.jpg";

import {
  DARK_USER_THEMES,
  IMAGE_USER_THEMES,
  USER_THEME_BACKGROUND_COLORS,
  USER_THEME_BACKGROUND_GRADIENTS,
  userThemeBackgroundImageSrc,
  userThemeBackgroundVideoSrc,
  UserThemeContext,
} from "~/helpers/userThemes";
import { type UserTheme } from "~/types";

import classes from "./UserThemeProvider.module.css";

export interface UserThemeProviderProps extends PropsWithChildren {}

const UserThemeProvider: FC<UserThemeProviderProps> = ({ children }) => {
  const [theme, setTheme] = useState<UserTheme | null>(null);
  const [videoSuspended, setVideoSuspended] = useState(false);
  const currentUser = useCurrentUser();

  // == Special-case background for specific user(s)
  // Show BKDK backdrop only when user is "kirsamansi" AND
  // either no theme is selected or the ad-hoc "bakudeku" theme is selected.
  const isBkdkUser =
    currentUser?.handle === "kirsamansi" && (!theme || theme === ("bakudeku" as any));
  const bkdkImageUrl = bkdkImage;

  // == Apply theme on document body
  const colorScheme = useComputedColorScheme("light");
  useEffect(() => {
    if (theme && !isBkdkUser) {
      document.documentElement.setAttribute("data-user-theme", theme);
      document.body.style.setProperty(
        "--mantine-color-body",
        USER_THEME_BACKGROUND_COLORS[theme],
      );
      const themeColorScheme = DARK_USER_THEMES.includes(theme)
        ? "dark"
        : "light";
      document.documentElement.setAttribute(
        "data-mantine-color-scheme",
        themeColorScheme,
      );
    } else {
      document.documentElement.removeAttribute("data-user-theme");
      document.body.style.removeProperty("--mantine-color-body");
      document.documentElement.setAttribute(
        "data-mantine-color-scheme",
        colorScheme,
      );
    }
  }, [theme, colorScheme, isBkdkUser]);

  // == Ensure layout background is transparent so backdrop shows for BKDK user
  useEffect(() => {
    if (isBkdkUser) {
      document.documentElement.setAttribute("data-user-theme", "bkdk");
      // Prefer dark UI to contrast most backgrounds
      document.documentElement.setAttribute("data-mantine-color-scheme", "dark");
      return () => {
        document.documentElement.removeAttribute("data-user-theme");
      };
    }
    return undefined;
  }, [isBkdkUser]);

  return (
    <UserThemeContext.Provider
      value={{
        theme,
        setTheme,
      }}
    >
      {isBkdkUser ? (
        <Box
          className={classes.backdrop}
          role="backdrop"
          style={{
            backgroundImage: `url(${bkdkImageUrl})`,
            backgroundColor: "#0b0b0b",
          }}
        />
      ) : (
        !!theme && (
        <Box
          className={classes.backdrop}
          role="backdrop"
          style={{
            backgroundImage: themeBackgroundMedia(theme),
            backgroundColor: USER_THEME_BACKGROUND_COLORS[theme],
          }}
        >
          {IMAGE_USER_THEMES.includes(theme) ? (
            <div className={classes.imageContainer}>
              <img
                className={classes.image}
                src={userThemeBackgroundImageSrc(theme)}
              />
              <div
                className={classes.imageBackdrop}
                style={{
                  backgroundImage: themeBackgroundMedia(theme),
                }}
              />
            </div>
          ) : (
            <video
              autoPlay
              muted
              loop
              playsInline
              src={userThemeBackgroundVideoSrc(theme)}
              onSuspend={({ currentTarget }) => {
                if (!videoSuspended && currentTarget.paused) {
                  currentTarget.play().then(undefined, reason => {
                    if (
                      reason instanceof Error &&
                      reason.name === "NotAllowedError"
                    ) {
                      setVideoSuspended(true);
                    }
                  });
                }
              }}
              {...(videoSuspended && { style: { display: "none" } })}
            />
          )}
        </Box>
        )
      )}
      {children}
    </UserThemeContext.Provider>
  );
};

export default UserThemeProvider;

const themeBackgroundMedia = (theme: UserTheme) => {
  const src = IMAGE_USER_THEMES.includes(theme)
    ? userThemeBackgroundImageSrc(theme)
    : userThemeBackgroundVideoSrc(theme);
  return `url(${src}), ${USER_THEME_BACKGROUND_GRADIENTS[theme]}`;
};
