# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActivityCouponSerializer`.
# Please instead update this file by running `bin/tapioca dsl ActivityCouponSerializer`.


class ActivityCouponSerializer
  sig { returns(ActivityCoupon) }
  def activity_coupon; end
end
