# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActivitySerializer`.
# Please instead update this file by running `bin/tapioca dsl ActivitySerializer`.


class ActivitySerializer
  sig { returns(Activity) }
  def activity; end
end
