# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActivityTemplateSerializer`.
# Please instead update this file by running `bin/tapioca dsl ActivityTemplateSerializer`.


class ActivityTemplateSerializer
  sig { returns(ActivityTemplate) }
  def activity_template; end
end
