# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdminsOnly`.
# Please instead update this file by running `bin/tapioca dsl AdminsOnly`.


module AdminsOnly
  mixes_in_class_methods ::Logging::ClassMethods
end
