# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AnnouncementSerializer`.
# Please instead update this file by running `bin/tapioca dsl AnnouncementSerializer`.


class AnnouncementSerializer
  sig { returns(Announcement) }
  def announcement; end
end
