# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AssociatedFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl AssociatedFriendSerializer`.


class AssociatedFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
