# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AuthenticatesUsers`.
# Please instead update this file by running `bin/tapioca dsl AuthenticatesUsers`.


module AuthenticatesUsers
  mixes_in_class_methods ::Logging::ClassMethods
end
