# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AuthorWorldProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl AuthorWorldProfileSerializer`.


class AuthorWorldProfileSerializer
  sig { returns(World) }
  def world; end
end
