# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EncouragementSerializer`.
# Please instead update this file by running `bin/tapioca dsl EncouragementSerializer`.


class EncouragementSerializer
  sig { returns(Encouragement) }
  def encouragement; end
end
