# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EncouragementNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl EncouragementNotificationPayloadSerializer`.


class EncouragementNotificationPayloadSerializer
  sig { returns(EncouragementNotificationPayload) }
  def payload; end
end
