# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EncouragementFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl EncouragementFriendSerializer`.


class EncouragementFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
