# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendActivityCouponSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendActivityCouponSerializer`.


class FriendActivityCouponSerializer
  sig { returns(T.untyped) }
  def friend_activity_coupon; end
end
