# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendInfoSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendInfoSerializer`.


class FriendInfoSerializer
  sig { returns(Friend) }
  def friend; end
end
