# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendProfileSerializer`.


class FriendProfileSerializer
  sig { returns(Friend) }
  def friend; end
end
