# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendNotificationSettingsSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendNotificationSettingsSerializer`.


class FriendNotificationSettingsSerializer
  sig { returns(Friend) }
  def friend; end
end
