# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendNotificationPayloadSerializer`.


class FriendNotificationPayloadSerializer
  sig { returns(FriendNotificationPayload) }
  def payload; end
end
