# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendViewSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendViewSerializer`.


class FriendViewSerializer
  sig { returns(Friend) }
  def friend; end
end
