# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FriendNotificationFriendPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl FriendNotificationFriendPayloadSerializer`.


class FriendNotificationFriendPayloadSerializer
  sig { returns(Friend) }
  def friend; end
end
