# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImageSerializer`.
# Please instead update this file by running `bin/tapioca dsl ImageSerializer`.


class ImageSerializer
  sig { returns(Image) }
  def image; end
end
