# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InvitationSerializer`.
# Please instead update this file by running `bin/tapioca dsl InvitationSerializer`.


class InvitationSerializer
  sig { returns(Invitation) }
  def invitation; end
end
