# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InvitationActivitySerializer`.
# Please instead update this file by running `bin/tapioca dsl InvitationActivitySerializer`.


class InvitationActivitySerializer
  sig { returns(Activity) }
  def activity; end
end
