# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `JoinedUserSerializer`.
# Please instead update this file by running `bin/tapioca dsl JoinedUserSerializer`.


class JoinedUserSerializer
  sig { returns(JoinedUser) }
  def joined_user; end
end
