# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `JoinRequestSerializer`.
# Please instead update this file by running `bin/tapioca dsl JoinRequestSerializer`.


class JoinRequestSerializer
  sig { returns(JoinRequest) }
  def join_request; end
end
