# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `JoinRequestNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl JoinRequestNotificationPayloadSerializer`.


class JoinRequestNotificationPayloadSerializer
  sig { returns(JoinRequestNotificationPayload) }
  def payload; end
end
