# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyJoinRequestNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyJoinRequestNotificationPayloadSerializer`.


class LegacyJoinRequestNotificationPayloadSerializer
  sig { returns(JoinRequestNotificationPayload) }
  def payload; end
end
