# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyPostNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyPostNotificationPayloadSerializer`.


class LegacyPostNotificationPayloadSerializer
  sig { returns(PostNotificationPayload) }
  def payload; end
end
