# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyPostReactionNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyPostReactionNotificationPayloadSerializer`.


class LegacyPostReactionNotificationPayloadSerializer
  sig { returns(PostReactionNotificationPayload) }
  def payload; end
end
