# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyNotificationPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyNotificationPostSerializer`.


class LegacyNotificationPostSerializer
  sig { returns(Post) }
  def post; end
end
