# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyNotificationSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyNotificationSerializer`.


class LegacyNotificationSerializer
  sig { returns(T.untyped) }
  def legacy_notification; end
end
