# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyUniversePostNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyUniversePostNotificationPayloadSerializer`.


class LegacyUniversePostNotificationPayloadSerializer
  sig { returns(UniversePostNotificationPayload) }
  def payload; end
end
