# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyPostReactionNotificationPayloadReactionSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyPostReactionNotificationPayloadReactionSerializer`.


class LegacyPostReactionNotificationPayloadReactionSerializer
  sig { returns(PostReaction) }
  def post_reaction; end
end
