# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyFriendNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyFriendNotificationPayloadSerializer`.


class LegacyFriendNotificationPayloadSerializer
  sig { returns(FriendNotificationPayload) }
  def payload; end
end
