# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyEncouragementNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyEncouragementNotificationPayloadSerializer`.


class LegacyEncouragementNotificationPayloadSerializer
  sig { returns(EncouragementNotificationPayload) }
  def payload; end
end
