# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LegacyNotificationFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl LegacyNotificationFriendSerializer`.


class LegacyNotificationFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
