# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniverseFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniverseFriendPostSerializer`.


class LocalUniverseFriendPostSerializer
  sig { returns(Post) }
  def post; end
end
