# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniverseAuthorPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniverseAuthorPostSerializer`.


class LocalUniverseAuthorPostSerializer
  sig { returns(Post) }
  def post; end
end
