# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniverseSelfPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniverseSelfPostSerializer`.


class LocalUniverseSelfPostSerializer
  sig { returns(Post) }
  def post; end
end
