# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniversePublicPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniversePublicPostSerializer`.


class LocalUniversePublicPostSerializer
  sig { returns(Post) }
  def post; end
end
