# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniverseWorldSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniverseWorldSerializer`.


class LocalUniverseWorldSerializer
  sig { returns(LocalUniverseWorld) }
  def local_universe_world; end
end
