# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LocalUniversePostSerializer`.
# Please instead update this file by running `bin/tapioca dsl LocalUniversePostSerializer`.


class LocalUniversePostSerializer
  sig { returns(LocalUniversePost) }
  def local_universe_post; end
end
