# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LoginRequestSerializer`.
# Please instead update this file by running `bin/tapioca dsl LoginRequestSerializer`.


class LoginRequestSerializer
  sig { returns(LoginRequest) }
  def login_request; end
end
