# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotificationFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl NotificationFriendSerializer`.


class NotificationFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
