# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotificationPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl NotificationPostSerializer`.


class NotificationPostSerializer
  sig { returns(Post) }
  def post; end
end
