# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotifiableFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl NotifiableFriendSerializer`.


class NotifiableFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
