# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PhoneVerificationRequestSerializer`.
# Please instead update this file by running `bin/tapioca dsl PhoneVerificationRequestSerializer`.


class PhoneVerificationRequestSerializer
  sig { returns(PhoneVerificationRequest) }
  def phone_verification_request; end
end
