# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PositionSerializer`.
# Please instead update this file by running `bin/tapioca dsl PositionSerializer`.


class PositionSerializer
  sig { returns(Position) }
  def position; end
end
