# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostViewSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostViewSerializer`.


class PostViewSerializer
  sig { returns(Post) }
  def post; end
end
