# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactionNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactionNotificationPayloadSerializer`.


class PostReactionNotificationPayloadSerializer
  sig { returns(PostReactionNotificationPayload) }
  def payload; end
end
