# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactorSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactorSerializer`.


class PostReactorSerializer
  sig { returns(PostReactor) }
  def post_reactor; end
end
