# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostShareSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostShareSerializer`.


class PostShareSerializer
  sig { returns(PostShare) }
  def post_share; end
end
