# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactionNotificationPayloadPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactionNotificationPayloadPostSerializer`.


class PostReactionNotificationPayloadPostSerializer
  sig { returns(Post) }
  def post; end
end
