# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostViewerSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostViewerSerializer`.


class PostViewerSerializer
  sig { returns(T.untyped) }
  def post_viewer; end
end
