# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostPromptSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostPromptSerializer`.


class PostPromptSerializer
  sig { returns(Prompt) }
  def prompt; end
end
