# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostStreakSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostStreakSerializer`.


class PostStreakSerializer
  sig { returns(PostStreak) }
  def post_streak; end
end
