# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostNotificationPayloadAuthorSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostNotificationPayloadAuthorSerializer`.


class PostNotificationPayloadAuthorSerializer
  sig { returns(User) }
  def user; end
end
