# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostNotificationPayloadSerializer`.


class PostNotificationPayloadSerializer
  sig { returns(PostNotificationPayload) }
  def payload; end
end
