# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostWithoutEncouragementSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostWithoutEncouragementSerializer`.


class PostWithoutEncouragementSerializer
  sig { returns(Post) }
  def post; end
end
