# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostStickerSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostStickerSerializer`.


class PostStickerSerializer
  sig { returns(PostSticker) }
  def post_sticker; end
end
