# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactionNotificationPayloadReactionSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactionNotificationPayloadReactionSerializer`.


class PostReactionNotificationPayloadReactionSerializer
  sig { returns(PostReaction) }
  def post_reaction; end
end
