# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostAlertNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostAlertNotificationPayloadSerializer`.


class PostAlertNotificationPayloadSerializer
  sig { returns(PostAlertNotificationPayload) }
  def payload; end
end
