# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactionSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactionSerializer`.


class PostReactionSerializer
  sig { returns(PostReaction) }
  def post_reaction; end
end
