# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostAlertNotificationPayloadPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostAlertNotificationPayloadPostSerializer`.


class PostAlertNotificationPayloadPostSerializer
  sig { returns(Post) }
  def post; end
end
