# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostAlertNotificationPayloadPostAlertSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostAlertNotificationPayloadPostAlertSerializer`.


class PostAlertNotificationPayloadPostAlertSerializer
  sig { returns(PostAlert) }
  def post_alert; end
end
