# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostNotificationPayloadPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostNotificationPayloadPostSerializer`.


class PostNotificationPayloadPostSerializer
  sig { returns(Post) }
  def post; end
end
