# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostSerializer`.


class PostSerializer
  sig { returns(Post) }
  def post; end
end
