# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostEncouragementSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostEncouragementSerializer`.


class PostEncouragementSerializer
  sig { returns(Encouragement) }
  def encouragement; end
end
