# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostReactionNotificationPayloadFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl PostReactionNotificationPayloadFriendSerializer`.


class PostReactionNotificationPayloadFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
