# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PromptDeckSerializer`.
# Please instead update this file by running `bin/tapioca dsl PromptDeckSerializer`.


class PromptDeckSerializer
  sig { returns(PromptDeck) }
  def prompt_deck; end
end
