# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PromptSerializer`.
# Please instead update this file by running `bin/tapioca dsl PromptSerializer`.


class PromptSerializer
  sig { returns(Prompt) }
  def prompt; end
end
