# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PushRegistrationSerializer`.
# Please instead update this file by running `bin/tapioca dsl PushRegistrationSerializer`.


class PushRegistrationSerializer
  sig { returns(PushRegistration) }
  def push_registration; end
end
