# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `QuotedPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl QuotedPostSerializer`.


class QuotedPostSerializer
  sig { returns(Post) }
  def post; end
end
