# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendTextBlastJob`.
# Please instead update this file by running `bin/tapioca dsl SendTextBlastJob`.


class SendTextBlastJob
  class << self
    sig do
      params(
        text_blast: ::TextBlast,
        block: T.nilable(T.proc.params(job: SendTextBlastJob).void)
      ).returns(T.any(SendTextBlastJob, FalseClass))
    end
    def perform_later(text_blast, &block); end

    sig { params(text_blast: ::TextBlast).void }
    def perform_now(text_blast); end
  end
end
