# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpaceSerializer`.
# Please instead update this file by running `bin/tapioca dsl SpaceSerializer`.


class SpaceSerializer
  sig { returns(Space) }
  def space; end
end
