# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpacePostSerializer`.
# Please instead update this file by running `bin/tapioca dsl SpacePostSerializer`.


class SpacePostSerializer
  sig { returns(SpacePost) }
  def space_post; end
end
