# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SuggestedFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl SuggestedFriendSerializer`.


class SuggestedFriendSerializer
  sig { returns(SuggestedFriend) }
  def suggested_friend; end
end
