# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SupabaseAuthentication`.
# Please instead update this file by running `bin/tapioca dsl SupabaseAuthentication`.


module SupabaseAuthentication
  mixes_in_class_methods ::Logging::ClassMethods
end
