# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TestMailer`.
# Please instead update this file by running `bin/tapioca dsl TestMailer`.


class TestMailer
  class << self
    sig { params(model: ::TestModel).returns(::ActionMailer::MessageDelivery) }
    def test_email(model); end
  end
end
