# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniversePostAssociatedFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniversePostAssociatedFriendSerializer`.


class UniversePostAssociatedFriendSerializer
  sig { returns(UniversePostAssociatedFriend) }
  def universe_post_associated_friend; end
end
