# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniversePostNotificationPayloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniversePostNotificationPayloadSerializer`.


class UniversePostNotificationPayloadSerializer
  sig { returns(UniversePostNotificationPayload) }
  def payload; end
end
