# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniverseWorldSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniverseWorldSerializer`.


class UniverseWorldSerializer
  sig { returns(UniverseWorld) }
  def universe_world; end
end
