# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniverseFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniverseFriendPostSerializer`.


class UniverseFriendPostSerializer
  sig { returns(Post) }
  def post; end
end
