# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniverseAuthorPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniverseAuthorPostSerializer`.


class UniverseAuthorPostSerializer
  sig { returns(Post) }
  def post; end
end
