# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniversePostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniversePostSerializer`.


class UniversePostSerializer
  sig { returns(Post) }
  def post; end
end
