# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniversePublicPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniversePublicPostSerializer`.


class UniversePublicPostSerializer
  sig { returns(Post) }
  def post; end
end
