# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UniverseWorldProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl UniverseWorldProfileSerializer`.


class UniverseWorldProfileSerializer
  sig { returns(UniverseWorldProfile) }
  def universe_world_profile; end
end
