# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserPublicPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserPublicPostSerializer`.


class UserPublicPostSerializer
  sig { returns(Post) }
  def post; end
end
