# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserUniversePublicPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserUniversePublicPostSerializer`.


class UserUniversePublicPostSerializer
  sig { returns(UserUniversePublicPost) }
  def user_universe_public_post; end
end
