# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserPostSerializer`.


class UserPostSerializer
  sig { returns(UserPost) }
  def user_post; end
end
