# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserUniverseFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserUniverseFriendPostSerializer`.


class UserUniverseFriendPostSerializer
  sig { returns(UserUniverseFriendPost) }
  def user_universe_friend_post; end
end
