# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserPostViewerSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserPostViewerSerializer`.


class UserPostViewerSerializer
  sig { returns(UserPostViewer) }
  def user_post_viewer; end
end
