# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserUniverseAuthorPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserUniverseAuthorPostSerializer`.


class UserUniverseAuthorPostSerializer
  sig { returns(UserUniverseAuthorPost) }
  def user_universe_author_post; end
end
