# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserProfileSerializer`.


class UserProfileSerializer
  sig { returns(User) }
  def user; end
end
