# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserUniverseAuthorPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserUniverseAuthorPostSerializer`.


class UserUniverseAuthorPostSerializer
  sig { returns(Post) }
  def post; end
end
