# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserUniverseFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserUniverseFriendPostSerializer`.


class UserUniverseFriendPostSerializer
  sig { returns(Post) }
  def post; end
end
