# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserWorldFriendProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserWorldFriendProfileSerializer`.


class UserWorldFriendProfileSerializer
  sig { returns(Friend) }
  def friend; end
end
