# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserFriendPostSerializer`.


class UserFriendPostSerializer
  sig { returns(Post) }
  def post; end
end
