# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserWorldPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserWorldPostSerializer`.


class UserWorldPostSerializer
  sig { returns(Post) }
  def post; end
end
