# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserWorldInvitationSerializer`.
# Please instead update this file by running `bin/tapioca dsl UserWorldInvitationSerializer`.


class UserWorldInvitationSerializer
  sig { returns(Invitation) }
  def invitation; end
end
