# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldInvitationSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldInvitationSerializer`.


class WorldInvitationSerializer
  sig { returns(Invitation) }
  def invitation; end
end
