# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldSerializer`.


class WorldSerializer
  sig { returns(User) }
  def user; end
end
