# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldFriendSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldFriendSerializer`.


class WorldFriendSerializer
  sig { returns(Friend) }
  def friend; end
end
