# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldFriendPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldFriendPostSerializer`.


class WorldFriendPostSerializer
  sig { returns(Post) }
  def post; end
end
