# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldPublicPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldPublicPostSerializer`.


class WorldPublicPostSerializer
  sig { returns(Post) }
  def post; end
end
