# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldPostSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldPostSerializer`.


class WorldPostSerializer
  sig { returns(WorldPost) }
  def world_post; end
end
