# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WorldProfileSerializer`.
# Please instead update this file by running `bin/tapioca dsl WorldProfileSerializer`.


class WorldProfileSerializer
  sig { returns(World) }
  def world; end
end
