/**
 * Generated by: Claude Sonnet 4
 * Last modified: 2024-12-28 09:00:00 UTC
 *
 * This code was AI-generated and may require human review and testing.
 */

import { useEffect, useState } from "react";

import { type Friend, type User } from "~/types";

export const JOIN_MESSAGE = "you're invited to join my smaller world";

export const formatJoinMessage = (joinUrl: string) =>
  `${JOIN_MESSAGE}: ${joinUrl}`;

const buildJoinUrl = (user: User, friend: Friend): string => {
  const joinPath = routes.users.show.path({
    id: user.handle,
    query: {
      friend_token: friend.access_token,
      intent: "join",
    },
  });
  const joinUrl = hrefToUrl(joinPath);
  return joinUrl.toString();
};

export const useJoinUrl = (user: User, friend: Friend): string | undefined => {
  const [joinUrl, setJoinUrl] = useState<string>();
  useEffect(() => {
    setJoinUrl(buildJoinUrl(user, friend));
  }, [user, friend]);
  return joinUrl;
};
